accounts/models.py
import datetime

from flask_login import UserMixin
from sqlalchemy import DateTime

from database import db


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), index=True, unique=True, nullable=False)
    username = db.Column(db.String(64), index=True, unique=False, nullable=False)
    hashed_password = db.Column(db.String(110), unique=False, nullable=False)

    def __init__(self, email: str, username: str, hashed_password: str):
        self.email = email
        self.username = username
        self.hashed_password = hashed_password

    def __repr__(self):
        return f"<User {self.username}>"


class Transaction(db.Model):
    __tablename__ = "transactions"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer)
    date = db.Column(DateTime, default=datetime.datetime.utcnow)
    transactions_sum = db.Column(db.Integer)
    sign = db.Column(db.Boolean)
    category_id = db.Column(db.Integer)

    def __init__(self, user_id: int, sign: bool, transactions_sum: int, category_id: int):
        self.user_id = user_id
        self.sign = sign
        self.transactions_sum = transactions_sum
        self.category_id = category_id


class Category(db.Model):
    __tablename__ = "category"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer)
    name_category = db.Column(db.String(64))

    def __init__(self, user_id, name_category):
        self.user_id = user_id
        self.name_category = name_category

accounts/controllers.py
from flask import request, redirect, url_for, flash, render_template, Blueprint, abort
from flask_login import login_user, login_required, logout_user, current_user

from accounts.services import find_by_username_and_password, NotFoundError, find_user_by_id
from werkzeug.security import generate_password_hash

from accounts.models import User
from accounts.services_for_db import add_users_to_db

accounts_blueprint = Blueprint('accounts', __name__, template_folder='templates')

POSTS_PER_PAGE = 10


@accounts_blueprint.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        remember_me = len(request.form.getlist('remember_me')) > 0
        try:
            user = find_by_username_and_password(email, password)
        except Exception as e:
            flash(str(e) or 'Unknown error')
            return redirect(url_for('accounts.login'))
        else:
            login_user(user, remember=remember_me)
            return redirect(url_for('company_management.main_page'))
    return render_template('accounts/login.html')


@accounts_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('company_management.main_page'))


@accounts_blueprint.route("/user/<int:user_id>", methods=["GET"])
@login_required
def user_info(user_id: int):
    try:
        user = find_user_by_id(user_id)
        return render_template('accounts/user_info.html', user=user)
    except NotFoundError:
        abort(404)


@accounts_blueprint.route("/user", methods=["GET"])
@login_required
def current_user_info():
    return render_template('accounts/user_info.html', user=current_user)


@accounts_blueprint.route('/register', methods=('GET', 'POST'))
def register_user():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        hashed_password = request.form.get('password')
        repeat_hashed_password = request.form.get('repeat_password')
        if not hashed_password:
            flash('Поля ввода пароля обязательно')
            return render_template('accounts/register.html')
        if hashed_password == repeat_hashed_password:
            if User.query.filter_by(email=email).first():
                flash('Пользователь с такой почтой уже существует')
            else:
                add_users_to_db(email, username, generate_password_hash(hashed_password))
                user = find_by_username_and_password(email, hashed_password)
                login_user(user)
                return redirect(url_for('company_management.main_page'))
        else:
            flash('Пароли не совпадают')
    return render_template('accounts/register.html')

app.py
import os

from flask import Flask, g
from flask_login import current_user
from flask_migrate import Migrate

from accounts.controllers import accounts_blueprint
from accounts.login_manager import login_manager
from accounts.info_users import user_blueprint
from company_management.controllers import company_management_blueprint
from database import db
from error_handlers import page_not_found
from accounts.functional import functional_blueprint
from local_configs import Configuration

app = Flask(__name__)
migrate = Migrate(app, db)


@app.before_request
def before_request():
    g.user = current_user


if not os.getenv('IS_PRODUCTION', None):
    app.config.from_object(Configuration)

db.init_app(app)
login_manager.init_app(app)
app.register_blueprint(accounts_blueprint, url_prefix='/accounts')
app.register_blueprint(company_management_blueprint, url_prefix='/')
app.register_blueprint(functional_blueprint, url_prefix='/functional')
app.register_blueprint(user_blueprint, url_prefix='/user')
app.register_error_handler(404, page_not_found)

if __name__ == '__main__':
    app.run()

company_management/__init__.py
from flask import Blueprint

company_management_blueprint = Blueprint('company_management', __name__)

company_management/controllers.py
from flask import Blueprint, render_template, g

from company_management.data_processing import data_for_today, data_for_weekday, data_for_mouth, data_for_year

company_management_blueprint = Blueprint('company_management', __name__, template_folder='templates')


@company_management_blueprint.route('/', methods=('GET',))
def main_page():
    data = []
    if g.user.is_authenticated:
        income_for_today, expenses_for_today, balance_for_today = data_for_today()  # this is why i like python
        income_for_weekday, expenses_for_weekday, balance_for_weekday = data_for_weekday()
        income_for_mouth, expenses_for_mouth, balance_for_mouth = data_for_mouth()
        income_for_year, expenses_for_year, balance_for_year = data_for_year()

        data = [
            income_for_today.first()[0],
            income_for_weekday.first()[0],
            income_for_mouth.first()[0],
            income_for_year.first()[0],
            expenses_for_today.first()[0],
            expenses_for_weekday.first()[0],
            expenses_for_mouth.first()[0],
            expenses_for_year.first()[0],
            balance_for_today.first()[0],
            balance_for_weekday.first()[0],
            balance_for_mouth.first()[0],
            balance_for_year.first()[0]
        ]

        for i in range(len(data)):
            if not data[i]:
                data[i] = 0

    return render_template('company_management/main_page.html', data=data)

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Track Money</title>
    <link rel="shortcut icon" href="../static/picture/money-bag-white.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
            crossorigin="anonymous"></script>
</head>

<body>
<section class="hero is-primary is-fullheight">
    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    {% if g.user.is_authenticated %}
                        <div class="navbar-header">
                            <div class="container-fluid">
                                <a class="navbar-brand" href="{{ url_for('company_management.main_page') }}"
                                   class="navbar-item">
                                    <img src="../static/picture/money-bag-white.png" width="50" height="50"
                                         class="d-inline-block align-text-top">
                                    Home
                                </a>
                            </div>
                        </div>
                        <div class="navbar-end">
                        <a class="navbar-brand" href="{{ url_for('functional.transaction') }}" class="navbar-item">
                            <img src="../static/picture/plus.png" width="60" height="20"
                                 class="d-inline-block align-text-top">
                        </a>

                        <a class="nav-link active" href="{{ url_for('functional.history_transactions') }}"
                           class="navbar-item">
                            История
                        </a>

                        <a class="nav-link active" href="{{ url_for('functional.statistics') }}" class="navbar-item">
                            Статистика
                        </a>

                        <a class="nav-link active" href="{{ url_for('functional.list_category') }}" class="navbar-item">
                            Список категорий
                        </a>

                        <a class="nav-link active" href="{{ url_for('functional.create_category') }}"
                           class="navbar-item">
                            Создать новую категорию
                        </a>

                        <a class="nav-link active" href="{{ url_for('user.info_myself') }}" class="navbar-item">
                            Профиль
                        </a>

                        <a class="nav-link active" href="{{ url_for('accounts.logout') }}" class="navbar-item">
                            Выход
                        </a>
                    {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</section>
</body>
</html>